INSERT INTO uf (sigla, descricao, bandeira) VALUES
('AC', 'Acre', NULL),
('AL', 'Alagoas', NULL),
('AP', 'Amapá', NULL),
('AM', 'Amazonas', NULL),
('BA', 'Bahia', NULL),
('CE', 'Ceará', NULL),
('DF', 'Distrito Federal', NULL),
('ES', 'Espírito Santo', NULL),
('GO', 'Goiás', NULL),
('MA', 'Maranhão', NULL),
('MT', 'Mato Grosso', NULL),
('MS', 'Mato Grosso do Sul', NULL),
('MG', 'Minas Gerais', NULL),
('PA', 'Pará', NULL),
('PB', 'Paraíba', NULL),
('PR', 'Paraná', NULL),
('PE', 'Pernambuco', NULL),
('PI', 'Piauí', NULL),
('RJ', 'Rio de Janeiro', NULL),
('RN', 'Rio Grande do Norte', NULL),
('RS', 'Rio Grande do Sul', NULL),
('RO', 'Rondônia', NULL),
('RR', 'Roraima', NULL),
('SC', 'Santa Catarina', NULL),
('SP', 'São Paulo', NULL),
('SE', 'Sergipe', NULL),
('TO', 'Tocantins', NULL);


-- Exemplo para algumas cidades, você pode expandir conforme necessário:
INSERT INTO cidade (nome, uf_id, codIBGE, wiki) VALUES
('São Paulo', (SELECT id FROM uf WHERE sigla = 'SP'), '3550308', NULL),
('Campinas', (SELECT id FROM uf WHERE sigla = 'SP'), '3509502', NULL),
('Rio de Janeiro', (SELECT id FROM uf WHERE sigla = 'RJ'), '3304557', NULL),
('Niterói', (SELECT id FROM uf WHERE sigla = 'RJ'), '3303302', NULL),
('Belo Horizonte', (SELECT id FROM uf WHERE sigla = 'MG'), '3106200', NULL),
('Curitiba', (SELECT id FROM uf WHERE sigla = 'PR'), '4106902', NULL),
('Porto Alegre', (SELECT id FROM uf WHERE sigla = 'RS'), '4314902', NULL),
('Fortaleza', (SELECT id FROM uf WHERE sigla = 'CE'), '2304400', NULL),
('Muriaé', (SELECT id FROM uf WHERE sigla = 'MG'), '3143906', NULL),
('Ervália', (SELECT id FROM uf WHERE sigla = 'MG'), '3124104', NULL),
('Rosário da Limeira', (SELECT id FROM uf WHERE sigla = 'MG'), '3156456', NULL),
('Ubá', (SELECT id FROM uf WHERE sigla = 'MG'), '3170107', NULL),
('Viçosa', (SELECT id FROM uf WHERE sigla = 'MG'), '3171303', NULL),
('Cataguases', (SELECT id FROM uf WHERE sigla = 'MG'), '3115300', NULL),
('Leopoldina', (SELECT id FROM uf WHERE sigla = 'MG'), '3138401', NULL),
('Juiz de Fora', (SELECT id FROM uf WHERE sigla = 'MG'), '3136702', NULL),
('São Geraldo', (SELECT id FROM uf WHERE sigla = 'MG'), '3160603', NULL);



INSERT INTO `cargo` (`descricao`, `statusRegistro`) VALUES
('Administrador de Sistemas', 1),
('Analista de Suporte', 1),
('Analista de Dados', 1),
('Analista de Recursos Humanos', 1),
('Analista de Marketing', 1),
('Analista Financeiro', 1),
('Arquiteto de Software', 1),
('Assistente Administrativo', 1),
('Assistente de Compras', 1),
('Assistente de Logística', 1),
('Atendente de Telemarketing', 1),
('Auxiliar Administrativo', 1),
('Auxiliar de Almoxarifado', 1),
('Auxiliar de Limpeza', 1),
('Auxiliar de Produção', 1),
('Auxiliar de RH', 1),
('Coordenador de Projetos', 1),
('Coordenador de Vendas', 1),
('Desenvolvedor Back-End', 1),
('Desenvolvedor Front-End', 1),
('Desenvolvedor Full Stack', 1),
('Designer Gráfico', 1),
('Diretor de Operações', 1),
('Diretor Financeiro', 1),
('Engenheiro de Produção', 1),
('Engenheiro de Software', 1),
('Estagiário de Administração', 1),
('Estagiário de Engenharia', 1),
('Estagiário de Marketing', 1),
('Estagiário de TI', 1),
('Gerente Comercial', 1),
('Gerente de Compras', 1),
('Gerente de Marketing', 1),
('Gerente de Projetos', 1),
('Gerente de Recursos Humanos', 1),
('Gerente Financeiro', 1),
('Instrutor de Treinamento', 1),
('Jardineiro', 1),
('Motorista', 1),
('Operador de Caixa', 1),
('Operador de Empilhadeira', 1),
('Operador de Máquinas', 1),
('Pedreiro', 1),
('Pintor Industrial', 1),
('Programador PHP', 1),
('Programador Python', 1),
('Programador Java', 1),
('Programador C#', 1),
('Recepcionista', 1),
('Secretária Executiva', 1),
('Supervisor de Logística', 1),
('Supervisor de Produção', 1),
('Técnico de Enfermagem', 1),
('Técnico de Informática', 1),
('Técnico de Segurança do Trabalho', 1),
('Vendedor Interno', 1),
('Vendedor Externo', 1),
('Web Designer', 1),
('Zelador', 1),
('Auxiliar de Estoque', 1),
('Auxiliar de Manutenção', 1),
('Barbeiro', 1),
('Cabeleireiro', 1),
('Camareira', 1),
('Chef de Cozinha', 1),
('Consultor de Vendas', 1),
('Costureira', 1),
('Eletricista', 1),
('Enfermeiro', 1),
('Engenheiro Civil', 1),
('Farmacêutico', 1),
('Fiscal de Loja', 1),
('Garçom', 1),
('Gestor de TI', 1),
('Marceneiro', 1),
('Mecânico de Automóveis', 1),
('Médico Clínico Geral', 1),
('Médico do Trabalho', 1),
('Montador de Móveis', 1),
('Nutricionista', 1),
('Operador de Telemarketing', 1),
('Padeiro', 1),
('Porteiro', 1),
('Professor de Educação Física', 1),
('Psicólogo Organizacional', 1),
('Representante Comercial', 1),
('Segurança Patrimonial', 1),
('Serralheiro', 1),
('Soldador', 1),
('Supervisor de Call Center', 1),
('Técnico em Edificações', 1),
('Técnico em Eletrotécnica', 1),
('Técnico em Mecânica', 1),
('Técnico em Meio Ambiente', 1),
('Técnico em Química', 1),
('Torneiro Mecânico', 1),
('Tradutor', 1),
('Vigia', 1),
('Zootecnista', 1);


INSERT INTO categoria (descricao, statusRegistro) VALUES
('Restaurante', 1),
('Farmácia', 1),
('Clínica Médica', 1),
('Supermercado', 1),
('Academia', 1),
('Loja de Roupas', 1);


INSERT INTO escolaridade (descricao, statusRegistro) VALUES
('Ensino Fundamental Incompleto', 1),
('Ensino Fundamental Completo', 1),
('Ensino Médio Incompleto', 1),
('Ensino Médio Completo', 1),
('Ensino Técnico', 1),
('Graduação Incompleta', 1),
('Graduação Completa', 1),
('Pós-Graduação', 1),
('Mestrado', 1),
('Doutorado', 1);
